### ISSUE TITLE
[Bug]: [VOD] Multi-Account issue with same source server

### ISSUE THREAD

**Issue by gardor007** [Dispatcharr/Dispatcharr#533]
### Describe the bug

Describe the bug
When streaming multiple VODs from an Emby Server through Dispatcharr, the second stream fails, even though multiple accounts are configured.

Expected behavior
Each configured account should be able to stream VOD content simultaneously from Emby without failure.

Actual behavior
With one VOD stream active in Emby, playback works correctly.
Starting a second VOD stream fails immediately.
Live TV streams are unaffected and function correctly with multiple simultaneous connections.

Additional context
All three provider accounts are configured identically in Dispatcharr.
This issue appears specific to VOD playback initiated from Emby; Live TV streaming works as expected.

### How can we recreate this bug?

Steps to reproduce

Configure multiple Dispatcharr accounts (e.g., 3) from the same VOD provider.
Start a VOD stream from Emby
Start a second VOD stream → fails.

2025-10-07 23:44:14,551 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Seeking to byte position: 0 (~0.0 MB)
2025-10-07 23:44:14,551 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Rapid request detected (1.5s) - likely seeking
2025-10-07 23:44:14,551 INFO apps.proxy.vod_proxy.views [VOD-CLIENT] Client info - IP: 192.168.222.247, User-Agent: Lavf/59.27.100...
2025-10-07 23:44:14,551 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Creating new session: vod_1759880654551_2352
2025-10-07 23:44:14,551 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Redirecting to path-based URL: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880654551_2352
2025-10-07 23:44:14,552 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Starting VOD stream request: movie/12667739-e446-478c-b3a9-38475da7fec4, session: vod_1759880654551_2352, profile: None
2025-10-07 23:44:14,553 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Full request path: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880654551_2352
2025-10-07 23:44:14,553 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Request method: GET
2025-10-07 23:44:14,553 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Request headers: {'Content-Type': '', 'Content-Length': '', 'User-Agent': 'Lavf/59.27.100', 'Accept': '*/*', 'Range': 'bytes=0-', 'Connection': 'close', 'Host': '192.168.222.31:9191', 'Icy-Metadata': '1'}
2025-10-07 23:44:14,553 INFO apps.proxy.vod_proxy.views [VOD-TIMESHIFT] Timeshift params - utc_start: None, utc_end: None, offset: None
2025-10-07 23:44:14,553 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Session ID: vod_1759880654551_2352
2025-10-07 23:44:14,553 INFO apps.proxy.vod_proxy.views [VOD-RANGE] Range header: bytes=0-
2025-10-07 23:44:14,553 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Seeking to byte position: 0 (~0.0 MB)
2025-10-07 23:44:14,553 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Rapid request detected (0.0s) - likely seeking
2025-10-07 23:44:14,553 INFO apps.proxy.vod_proxy.views [VOD-CLIENT] Client info - IP: 192.168.222.247, User-Agent: Lavf/59.27.100...
2025-10-07 23:44:14,553 INFO apps.proxy.vod_proxy.views [CONTENT-LOOKUP] Looking up movie with UUID 12667739-e446-478c-b3a9-38475da7fec4
2025-10-07 23:44:14,562 INFO apps.proxy.vod_proxy.views [CONTENT-FOUND] Movie: 4K-FR - Swiped (2025) (ID: 10987)
2025-10-07 23:44:14,567 INFO apps.proxy.vod_proxy.views [PROVIDER-SELECTED] Using provider: provider account 1 (priority: 0)
2025-10-07 23:44:14,567 INFO apps.proxy.vod_proxy.views [VOD-CONTENT] Found content: 4K-FR - Swiped (2025)
2025-10-07 23:44:14,567 INFO apps.proxy.vod_proxy.views [VOD-ACCOUNT] Using M3U account: provider account 1
2025-10-07 23:44:14,568 INFO apps.proxy.vod_proxy.views [VOD-URL] Relation type: M3UMovieRelation
2025-10-07 23:44:14,568 INFO apps.proxy.vod_proxy.views [VOD-URL] Account type: XC
2025-10-07 23:44:14,568 INFO apps.proxy.vod_proxy.views [VOD-URL] Stream ID: 1555657
2025-10-07 23:44:14,568 INFO apps.proxy.vod_proxy.views [VOD-URL] Built URL from get_stream_url(): https://provider/movie/username/password/1555657.mkv
2025-10-07 23:44:14,568 INFO apps.proxy.vod_proxy.views [VOD-CONTENT] Content URL: https://provider/movie/username/password/1555657.mkv
2025-10-07 23:44:14,571 ERROR apps.proxy.vod_proxy.views [PROFILE-SELECTION] All profiles at capacity for M3U account 5, rejecting request
2025-10-07 23:44:14,572 ERROR apps.proxy.vod_proxy.views [VOD-ERROR] No suitable M3U profile found for movie 12667739-e446-478c-b3a9-38475da7fec4
2025-10-07 23:44:14,572 ERROR django.request Service Unavailable: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880654551_2352
2025-10-07 23:44:14,000 INFO uwsgi.requests Worker ID: 1 GET 503 /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880654551_2352 20ms
2025-10-07 23:44:16,082 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Starting VOD stream request: movie/12667739-e446-478c-b3a9-38475da7fec4, session: None, profile: None
2025-10-07 23:44:16,082 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Full request path: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4
2025-10-07 23:44:16,082 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Request method: GET
2025-10-07 23:44:16,082 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Request headers: {'Content-Type': '', 'Content-Length': '', 'User-Agent': 'Lavf/59.27.100', 'Accept': '*/*', 'Range': 'bytes=0-', 'Connection': 'close', 'Host': '192.168.222.31:9191', 'Icy-Metadata': '1'}
2025-10-07 23:44:16,082 INFO apps.proxy.vod_proxy.views [VOD-TIMESHIFT] Timeshift params - utc_start: None, utc_end: None, offset: None
2025-10-07 23:44:16,082 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Session ID: None
2025-10-07 23:44:16,082 INFO apps.proxy.vod_proxy.views [VOD-RANGE] Range header: bytes=0-
2025-10-07 23:44:16,082 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Seeking to byte position: 0 (~0.0 MB)
2025-10-07 23:44:16,082 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Rapid request detected (1.5s) - likely seeking
2025-10-07 23:44:16,083 INFO apps.proxy.vod_proxy.views [VOD-CLIENT] Client info - IP: 192.168.222.247, User-Agent: Lavf/59.27.100...
2025-10-07 23:44:16,083 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Creating new session: vod_1759880656083_9379
2025-10-07 23:44:16,083 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Redirecting to path-based URL: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880656083_9379
2025-10-07 23:44:16,097 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Starting VOD stream request: movie/12667739-e446-478c-b3a9-38475da7fec4, session: vod_1759880656083_9379, profile: None
2025-10-07 23:44:16,097 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Full request path: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880656083_9379
2025-10-07 23:44:16,097 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Request method: GET
2025-10-07 23:44:16,097 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Request headers: {'Content-Type': '', 'Content-Length': '', 'User-Agent': 'Lavf/59.27.100', 'Accept': '*/*', 'Range': 'bytes=0-', 'Connection': 'close', 'Host': '192.168.222.31:9191', 'Icy-Metadata': '1'}
2025-10-07 23:44:16,097 INFO apps.proxy.vod_proxy.views [VOD-TIMESHIFT] Timeshift params - utc_start: None, utc_end: None, offset: None
2025-10-07 23:44:16,098 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Session ID: vod_1759880656083_9379
2025-10-07 23:44:16,098 INFO apps.proxy.vod_proxy.views [VOD-RANGE] Range header: bytes=0-
2025-10-07 23:44:16,098 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Seeking to byte position: 0 (~0.0 MB)
2025-10-07 23:44:16,098 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Rapid request detected (0.0s) - likely seeking
2025-10-07 23:44:16,098 INFO apps.proxy.vod_proxy.views [VOD-CLIENT] Client info - IP: 192.168.222.247, User-Agent: Lavf/59.27.100...
2025-10-07 23:44:16,098 INFO apps.proxy.vod_proxy.views [CONTENT-LOOKUP] Looking up movie with UUID 12667739-e446-478c-b3a9-38475da7fec4
2025-10-07 23:44:16,107 INFO apps.proxy.vod_proxy.views [CONTENT-FOUND] Movie: 4K-FR - Swiped (2025) (ID: 10987)
2025-10-07 23:44:16,111 INFO apps.proxy.vod_proxy.views [PROVIDER-SELECTED] Using provider: provider account 1 (priority: 0)
2025-10-07 23:44:16,111 INFO apps.proxy.vod_proxy.views [VOD-CONTENT] Found content: 4K-FR - Swiped (2025)
2025-10-07 23:44:16,111 INFO apps.proxy.vod_proxy.views [VOD-ACCOUNT] Using M3U account: provider account 1
2025-10-07 23:44:16,111 INFO apps.proxy.vod_proxy.views [VOD-URL] Relation type: M3UMovieRelation
2025-10-07 23:44:16,111 INFO apps.proxy.vod_proxy.views [VOD-URL] Account type: XC
2025-10-07 23:44:16,111 INFO apps.proxy.vod_proxy.views [VOD-URL] Stream ID: 1555657
2025-10-07 23:44:16,111 INFO apps.proxy.vod_proxy.views [VOD-URL] Built URL from get_stream_url(): https://provider/movie/username/password/1555657.mkv
2025-10-07 23:44:16,111 INFO apps.proxy.vod_proxy.views [VOD-CONTENT] Content URL: https://provider/movie/username/password/1555657.mkv
2025-10-07 23:44:16,114 ERROR apps.proxy.vod_proxy.views [PROFILE-SELECTION] All profiles at capacity for M3U account 5, rejecting request
2025-10-07 23:44:16,114 ERROR apps.proxy.vod_proxy.views [VOD-ERROR] No suitable M3U profile found for movie 12667739-e446-478c-b3a9-38475da7fec4
2025-10-07 23:44:16,114 ERROR django.request Service Unavailable: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880656083_9379
2025-10-07 23:44:16,000 INFO uwsgi.requests Worker ID: 1 GET 503 /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880656083_9379 18ms
2025-10-07 23:44:17,613 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Starting VOD stream request: movie/12667739-e446-478c-b3a9-38475da7fec4, session: None, profile: None
2025-10-07 23:44:17,613 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Full request path: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4
2025-10-07 23:44:17,613 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Request method: GET
2025-10-07 23:44:17,613 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Request headers: {'Content-Type': '', 'Content-Length': '', 'User-Agent': 'Lavf/59.27.100', 'Accept': '*/*', 'Range': 'bytes=0-', 'Connection': 'close', 'Host': '192.168.222.31:9191', 'Icy-Metadata': '1'}
2025-10-07 23:44:17,613 INFO apps.proxy.vod_proxy.views [VOD-TIMESHIFT] Timeshift params - utc_start: None, utc_end: None, offset: None
2025-10-07 23:44:17,613 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Session ID: None
2025-10-07 23:44:17,613 INFO apps.proxy.vod_proxy.views [VOD-RANGE] Range header: bytes=0-
2025-10-07 23:44:17,613 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Seeking to byte position: 0 (~0.0 MB)
2025-10-07 23:44:17,613 INFO apps.proxy.vod_proxy.views [VOD-CLIENT] Client info - IP: 192.168.222.247, User-Agent: Lavf/59.27.100...
2025-10-07 23:44:17,614 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Creating new session: vod_1759880657614_4428
2025-10-07 23:44:17,614 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Redirecting to path-based URL: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880657614_4428
2025-10-07 23:44:17,628 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Starting VOD stream request: movie/12667739-e446-478c-b3a9-38475da7fec4, session: vod_1759880657614_4428, profile: None
2025-10-07 23:44:17,629 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Full request path: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880657614_4428
2025-10-07 23:44:17,629 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Request method: GET
2025-10-07 23:44:17,629 INFO apps.proxy.vod_proxy.views [VOD-REQUEST] Request headers: {'Content-Type': '', 'Content-Length': '', 'User-Agent': 'Lavf/59.27.100', 'Accept': '*/*', 'Range': 'bytes=0-', 'Connection': 'close', 'Host': '192.168.222.31:9191', 'Icy-Metadata': '1'}
2025-10-07 23:44:17,629 INFO apps.proxy.vod_proxy.views [VOD-TIMESHIFT] Timeshift params - utc_start: None, utc_end: None, offset: None
2025-10-07 23:44:17,629 INFO apps.proxy.vod_proxy.views [VOD-SESSION] Session ID: vod_1759880657614_4428
2025-10-07 23:44:17,629 INFO apps.proxy.vod_proxy.views [VOD-RANGE] Range header: bytes=0-
2025-10-07 23:44:17,629 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Seeking to byte position: 0 (~0.0 MB)
2025-10-07 23:44:17,629 INFO apps.proxy.vod_proxy.views [VOD-SEEK] Rapid request detected (0.0s) - likely seeking
2025-10-07 23:44:17,629 INFO apps.proxy.vod_proxy.views [VOD-CLIENT] Client info - IP: 192.168.222.247, User-Agent: Lavf/59.27.100...
2025-10-07 23:44:17,629 INFO apps.proxy.vod_proxy.views [CONTENT-LOOKUP] Looking up movie with UUID 12667739-e446-478c-b3a9-38475da7fec4
2025-10-07 23:44:17,637 INFO apps.proxy.vod_proxy.views [CONTENT-FOUND] Movie: 4K-FR - Swiped (2025) (ID: 10987)
2025-10-07 23:44:17,642 INFO apps.proxy.vod_proxy.views [PROVIDER-SELECTED] Using provider: provider account 1 (priority: 0)
2025-10-07 23:44:17,642 INFO apps.proxy.vod_proxy.views [VOD-CONTENT] Found content: 4K-FR - Swiped (2025)
2025-10-07 23:44:17,642 INFO apps.proxy.vod_proxy.views [VOD-ACCOUNT] Using M3U account: provider account 1
2025-10-07 23:44:17,642 INFO apps.proxy.vod_proxy.views [VOD-URL] Relation type: M3UMovieRelation
2025-10-07 23:44:17,642 INFO apps.proxy.vod_proxy.views [VOD-URL] Account type: XC
2025-10-07 23:44:17,642 INFO apps.proxy.vod_proxy.views [VOD-URL] Stream ID: 1555657
2025-10-07 23:44:17,642 INFO apps.proxy.vod_proxy.views [VOD-URL] Built URL from get_stream_url(): https://provider/movie/username/password/1555657.mkv
2025-10-07 23:44:17,642 INFO apps.proxy.vod_proxy.views [VOD-CONTENT] Content URL: https://provider/movie/username/password/1555657.mkv
2025-10-07 23:44:17,645 ERROR apps.proxy.vod_proxy.views [PROFILE-SELECTION] All profiles at capacity for M3U account 5, rejecting request
2025-10-07 23:44:17,645 ERROR apps.proxy.vod_proxy.views [VOD-ERROR] No suitable M3U profile found for movie 12667739-e446-478c-b3a9-38475da7fec4
2025-10-07 23:44:17,645 ERROR django.request Service Unavailable: /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880657614_4428
2025-10-07 23:44:17,000 INFO uwsgi.requests Worker ID: 2 GET 503 /proxy/vod/movie/12667739-e446-478c-b3a9-38475da7fec4/vod_1759880657614_4428 17ms

### Dispatcharr Version

v0.10.3

### Docker Version

28.1.1+1

### What's in your Docker Compose file?

services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    container_name: dispatcharr
    ports:
      - 9191:9191
    volumes:
      - dispatcharr_data:/data
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info

volumes:
  dispatcharr_data:

### Client Information

Emby Server [4.8.11.0]

**Comment by PiratesIRC** [comment]
I am having the same error " All profiles at capacity for M3U account", without using Emby. I have tried adjusting my m3u provider account max streams but the issue still occurs. Live streaming works fine; this error is just when trying to play any VOD.

**Comment by PiratesIRC** [comment]
I believe this is related to https://github.com/Dispatcharr/Dispatcharr/issues/451
Despite ample time for the auto cleanup to occur, I was still having this issue. I was able to resolve it by manually cleaning up the Redis:
```
docker exec -it <name of dispatcharr container> redis-cli
GET profile_connections:<m3u account id>
DEL profile_connections:<m3u account id>
GET profile_connections:<m3u account id>
```
  
In my case, my m3u account ID was 2 and my docker container is named 'dispatcharr':

> user@debian:~$ docker exec -it dispatcharr redis-cli  
> 127.0.0.1:6379> GET profile_connections:2  
> "14" <--------- showing 14 connections?!
> 127.0.0.1:6379> DEL profile_connections:2
> (integer) 1
> 127.0.0.1:6379> GET profile_connections:2  
> (nil) <--------- no more active connections

**Comment by cedric-marcoux** [comment]
hello, i've fixed the issue with this plugin
https://github.com/cedric-marcoux/dispatcharr_vod_fix
Juste download the zip on github and install it as a plugin, please rename archive as  dispatcharr_vod_fix.zip instead of dispatcharr_vod_fix-main.zip

Regards

**Comment by slamanna212** [comment]
Can you please try the latest version and let me know if the issue still exists?

**Comment by gardor007** [comment]
> Can you please try the latest version and let me know if the issue still exists?

Hello,
I did test yesterday with the plugin and wasn't working
I've just tested without plugin and still don't work.

I can start 1 stream without any issue but as soon as i start a secondary stream it fails right away.

Thanks

**Comment by Yaya48** [comment]
Hello, Having the same bug here to

**Comment by CodeBormen** [comment]
For anyone having this issue, I have introduced a fix in PR #983. If anyone would like to build the change for testing, would appreciate it, if not no worries.

**Comment by SergeantPanda** [comment]
Available in dev.
