### ISSUE TITLE
[Feature]: Bulk add Streams to existing channels

### ISSUE THREAD

**Issue by nilleiz** [Dispatcharr/Dispatcharr#611]
### Is your feature request related to a problem?

I have got 2 sources of m3u channels, that I want to configure as failover. 
They both pretty much have the same channel order.
When I add all the channels from source A, I need to configure each and every single channel with the fallback stream from source B.

### Describe the solution you'd like

I would like to have an option to mark all channels on channels list on the left side that I want to add a secondary stream to, then mark the streams on the right from source B that I need to add, and then click "bulk add streams to channels".

### Additional context

Nothing Extra

**Comment by jonzey231** [comment]
https://github.com/PiratesIRC/Stream-Mapparr

**Comment by nilleiz** [comment]
Awesome, I'll give it a try!

**Comment by Goldenfreddy0703** [comment]
Hey @jonzey231 , I gave your plug-in a try combining over 4 of the same m3u Playlist with 7000 channels each but it keeps timing out for me with a 504 error. Any idea on what I can do?

Thanks

Btw the only difference with the 4 m3u playlists is just my xtreme user and password which is used for the stream Urls so thats about it, everything else is the same.

**Comment by jonzey231** [comment]
> Hey [@jonzey231](https://github.com/jonzey231) , I gave your plug-in a try combining over 4 of the same m3u Playlist with 7000 channels each but it keeps timing out for me with a 504 error. Any idea on what I can do?
> 
> Thanks
> 
> Btw the only difference with the 4 m3u playlists is just my xtreme user and password which is used for the stream Urls so thats about it, everything else is the same.

Hello, the only plugin I created was deprecated some time ago. Which plugin are you referencing?

**Comment by Goldenfreddy0703** [comment]
> Hello, the only plugin I created was deprecated some time ago. Which plugin are you referencing?

Oh....my bad, it was very late and I thought you owned this plugin: https://github.com/PiratesIRC/Stream-Mapparr

Sorry about that, I should have asked @PiratesIRC about that.

This was the error im getting:
`out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.24.0 (Ubuntu)</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

**Comment by PiratesIRC** [comment]
@Goldenfreddy0703 this should be fixed in v0.6.0b https://github.com/PiratesIRC/Stream-Mapparr/releases

**Comment by Goldenfreddy0703** [comment]
> [@Goldenfreddy0703](https://github.com/Goldenfreddy0703) this should be fixed in v0.6.0b https://github.com/PiratesIRC/Stream-Mapparr/releases

@PiratesIRC Thank you so much! I’m really glad to see this fixed. I tried troubleshooting it on my own but wasn’t able to get anywhere. I’ll be testing the update in a few hours and I truly appreciate the quick response.

I’ll let you know whether it fully resolves the issue.
Again, Thank you so much!!!!

**Comment by Goldenfreddy0703** [comment]
Hey @PiratesIRC  I actually tested right now and it looks like the same error is still happening unfortunately. Im not sure why, Im using my docker server and everything to run this but no luck. 

`Failed to run plugin action: 504 - <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.24.0 (Ubuntu)</center> </body> </html>  `

**Comment by PiratesIRC** [comment]
> Hey [@PiratesIRC](https://github.com/PiratesIRC) I actually tested right now and it looks like the same error is still happening unfortunately. Im not sure why, Im using my docker server and everything to run this but no luck.
> 
> `Failed to run plugin action: 504 - <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.24.0 (Ubuntu)</center> </body> </html> `

come on over to Discord and we can troubleshoot https://discord.com/channels/1340492560220684331/1423101426036506664
